function request(method : string, url : string, data : any = {}) : Promise<any> {
	return new Promise((s, f) => {
		uni.request<any>({
			url,
			data,
			method,
			success: (res : RequestSuccess<any>) => s(res.data as any),
			fail: f
		})

	})
}
export function get(url : string, data : any = {}) : Promise<any> {
	return request("GET", url, data)
}
export function post(url : string, data : any = {}) : Promise<any> {
	return request("Post", url, data)
}